/**
 *
 * $Id$
 */
package RoleteWheel.validation;


/**
 * A sample validator interface for {@link RoleteWheel.Feature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FeatureValidator {
	boolean validate();

	boolean validateClassname(String value);
	boolean validateId(int value);
	boolean validateName(String value);
	boolean validateTau(double value);
	boolean validateEta(double value);
	boolean validateNumeratorP(double value);
}
